repos:
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.63.11
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your codebase.
        entry: trufflehog git file://. --since-commit HEAD --only-verified --fail
        language: system
        stages: ["commit"]
