"""add scan_status and last_scan_at to repositories

Revision ID: 0d67974d93cf
Revises: 20311ed141eb
Create Date: 2026-05-11 17:45:02.300225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d67974d93cf'
down_revision: Union[str, Sequence[str], None] = '20311ed141eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repositories', sa.Column('scan_status', sa.String(), nullable=False))
    op.add_column('repositories', sa.Column('last_scan_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repositories', 'last_scan_at')
    op.drop_column('repositories', 'scan_status')
    # ### end Alembic commands ###
