"""Align tables with master plan

Revision ID: 20311ed141eb
Revises: 840dd4bdbee7
Create Date: 2026-05-05 02:51:13.804864

"""
from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '20311ed141eb'
down_revision: str | Sequence[str] | None = '840dd4bdbee7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=False),
    sa.Column('plan_tier', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('docs_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docs_versions_endpoint_id'), 'docs_versions', ['endpoint_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_version_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doc_version_id'], ['docs_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_doc_version_id'), 'chunks', ['doc_version_id'], unique=False)
    op.create_index('ix_chunks_embedding', 'chunks', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('doc_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_version_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doc_version_id'], ['docs_versions.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_reviews_doc_version_id'), 'doc_reviews', ['doc_version_id'], unique=False)
    op.drop_table('documentations')
    op.add_column('endpoints', sa.Column('status', sa.String(), nullable=False))
    op.add_column('endpoints', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_endpoints_repo_id'), 'endpoints', ['repo_id'], unique=False)
    op.create_index(op.f('ix_endpoints_status'), 'endpoints', ['status'], unique=False)
    op.add_column('repositories', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_repositories_owner_id'), 'repositories', ['owner_id'], unique=False)
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_index(op.f('ix_repositories_owner_id'), table_name='repositories')
    op.drop_column('repositories', 'deleted_at')
    op.drop_index(op.f('ix_endpoints_status'), table_name='endpoints')
    op.drop_index(op.f('ix_endpoints_repo_id'), table_name='endpoints')
    op.drop_column('endpoints', 'deleted_at')
    op.drop_column('endpoints', 'status')
    op.create_table('documentations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('endpoint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('quality_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_approved', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['endpoints.id'], name=op.f('documentations_endpoint_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('documentations_pkey'))
    )
    op.drop_index(op.f('ix_doc_reviews_doc_version_id'), table_name='doc_reviews')
    op.drop_table('doc_reviews')
    op.drop_index('ix_chunks_embedding', table_name='chunks', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_chunks_doc_version_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_docs_versions_endpoint_id'), table_name='docs_versions')
    op.drop_table('docs_versions')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
